### PR TITLE
Invenio114 deposit dates text - vanillajs

### PR DESCRIPTION
**Pull request by teikmeout**
[Jira ticket invenio-114](https://jira.nyu.edu/browse/INVENIO-114)

This PR will add the following:
- deposit form > Recommended Information > Dates: a vanilla JS solution that changes the title from "Dates" to "Additional Dates"

To test this PR:
- `invenio-cli services start`
- `invenio-cli packages install site` (runs webpack build too)
- `invenio-cli run`
- [navigate to deposit](https://127.0.0.1:5000/uploads/new) > login > recommended information: observe date addition subtitle says "Additional Dates" and not "Dates"
  - checkout `dismorfo/ultraviolet-nightwatch` branch `invenio114-dates-text` and run the instructions for [PR3](https://github.com/dismorfo/ultraviolet-nightwatch/pull/3)

Thank you for your review.

### CODE REVIEW

**Review by dismorfo — CHANGES_REQUESTED** [review]
Please follow the instructions for "[Creating custom code and views](https://inveniordm.docs.cern.ch/develop/howtos/custom_code/#creating-custom-code-and-views)" and "[How to add JavaScript files](https://inveniordm.docs.cern.ch/develop/howtos/add_javascript/)". Let me know if you need more help, and I can add the code. @ekate provided instructions on how to do this in our current instance.

Also, you can use a different selector to target the DOM element (e.g., 'label[for="metadata.dates"]')

Example code:

```
site/
├── ultraviolet
│   ├── assets
│   │   └── semantic-ui
│   │       ├── js
│   │       │   └── ultraviolet
│   │       │       └── ultraviolet.js
```

```
document.addEventListener('DOMContentLoaded', async () => {

  // https://stackoverflow.com/questions/5525071/how-to-wait-until-an-element-exists
  async function waitForElm(selector) {
    return new Promise(resolve => {
      if (document.querySelector(selector)) {
        return resolve(document.querySelector(selector))
      }    
      const observer = new MutationObserver(mutations => {
        if (document.querySelector(selector)) {
          observer.disconnect()
          resolve(document.querySelector(selector))
        }
      })    
      observer.observe(document.body, { childList: true, subtree: true })
    })
  }

  // INVENIO-114
  // Change text for "Dates" on deposit form to "Additional Dates"
  const metadataDatesField = await waitForElm('label[for="metadata.dates"]')
  if (metadataDatesField) {
    metadataDatesField.innerHTML = metadataDatesField.innerHTML.replace('Dates', 'Additional Dates')
  }

})
```

File: webpack.py
```
"""JS/CSS Webpack bundles for UltraViolet."""

from invenio_assets.webpack import WebpackThemeBundle

theme = WebpackThemeBundle(
    __name__,
    "assets",
    default="semantic-ui",
    themes={
        "semantic-ui": dict(
            entry={
                "ultraviolet": "./js/ultraviolet/ultraviolet.js"
            },
            dependencies={
            },            
        ),
    },
)
```

File: deposit.html

```
templates/
└── semantic-ui
    ├── invenio_app_rdm
    │   ├── records
    │   │   ├── deposit.html

```

```
{%- block javascript %}
    {{ super() }}
    {{ webpack['invenio-app-rdm-deposit.js'] }}
    {{ webpack['ultraviolet.js'] }}
{%- endblock %}
```

**Comment by teikmeout** [comment]
Ok @dismorfo we should be good to go to review this PR. Thank you for the review.

**Comment by teikmeout** [comment]
Ok @dismorfo. I believe this one is ready for review. 
Thank you for your time.

**Review by dismorfo — APPROVED** [review]
Looks good and ready to go.

**Review by ekate — APPROVED** [review]

**Pull request merged**
