### PR TITLE
58 add commid to upload

### PR DESCRIPTION
**Pull request by ekate**
The request re-uses PR 185 but puts default community slug to invenio.cfg instead of the template

### CODE REVIEW

**Comment by dismorfo** [comment]
@ekate I'm almost done with my review of the pull request [186](https://github.com/nyudlts/ultraviolet/pull/186). Pull request [186](https://github.com/nyudlts/ultraviolet/pull/186) and [this](https://github.com/nyudlts/ultraviolet/pull/187) pull request are adding the same file [invenio.cfg](https://github.com/nyudlts/ultraviolet/pull/187/files#diff-35ea7d0c9f0d3771b33ec0ac671404047bdff444801fcf084c39437c21107ebf) and similar update. 

I think we should remove that change (adding invenio.cfg) from [186](https://github.com/nyudlts/ultraviolet/pull/186).

[This](https://github.com/nyudlts/ultraviolet/pull/187) pull request should be about the change to invenio.cfg (adding DEFAULT_COMMUNITY). I also suggest removing the file: [templates/semantic-ui/invenio_app_rdm/users/uploads.html](https://github.com/nyudlts/ultraviolet/pull/187/files#diff-89da5cbe84a00ed7828b1418f524fec63487cbffbabc853a6f8d83770b7d983a) from this pull request and accepting pull request [185](https://github.com/nyudlts/ultraviolet/pull/185).

NOTE that [185](https://github.com/nyudlts/ultraviolet/pull/185) already includes the change requested by you in the last commit ([reading the default community value from the configuration file](https://github.com/nyudlts/ultraviolet/pull/185/commits/47d4b3792f9d6f4e1ac30cceeeb24551f63dd96a))

**Comment by ekate** [comment]
@dismorfo that was a branch/PR to show you suggested change. I think we can will delete it.

**Comment by dismorfo** [comment]
@ekate I still think there is value in accepting this pull request with just the update to the file [invenio.cfg](https://github.com/nyudlts/ultraviolet/pull/187/files#diff-35ea7d0c9f0d3771b33ec0ac671404047bdff444801fcf084c39437c21107ebf)

Would you like to do that? Or would you prefer to close this pull request and create a new pull request with the update to the file: [invenio.cfg](https://github.com/nyudlts/ultraviolet/pull/187/files#diff-35ea7d0c9f0d3771b33ec0ac671404047bdff444801fcf084c39437c21107ebf)?

**Comment by ekate** [comment]
@dismorfo I will close that one and resubmit another one just for invenio.cfg as this one has issues with tests

**Pull request closed without merging**
