### PR TITLE
(issue #40) Adds ROR affiliations for creators in upload form using culled list

### PR DESCRIPTION
**Pull request by nmwolf**
Responds to Issue number 40 by addressing question of upload creator affiliations. To minimize the build time required for large vocabularies lists, this PR provides a shorter culled list of NYU-only affiliations from the master list at https://inveniordm.docs.cern.ch/customize/vocabularies/affiliations/. These affiliations are listed in app_data/vocabularies/affiliations_ror.yaml. It also updates app_data/vocabularies.yaml to include affiliations in the master set of vocabularies.

See issue number 40 for unresolved issue not related to affiliations, which is UV access limiting by NYU status, specifically the need to provide an extra TOU step for undergraduate users.

### CODE REVIEW

**Comment by andrewbattista** [comment]
This looks great to me! Thanks @nmwolf

**Comment by ekate** [comment]
@nmwolf , @andrewbattista were you able to re-build your index and get the new values in the UI ?

**Comment by andrewbattista** [comment]
@ekate Yes, I was able to do this and it works! I didn't see any issues at all. Ditto for my PR on creator roles

**Comment by ekate** [comment]
@andrewbattista have you just re-build one index or the whole setup. I am asking because when I try to re-build just one index I do not see the changes (probably just me)

**Review by ekate — APPROVED** [review]

**Pull request merged**
